<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>ContextMini</AssemblyName>
    <RootNamespace>ContextMini</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContextMini.Core\ContextMini.Core.csproj" />
  </ItemGroup>
</Project>
